version: "3"
services:
  triton:
    image: "nvcr.io/nvidia/tritonserver:22.06-py3"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: ["tritonserver","--model-repository=${S3_BUCKET_NAME}"]

  boke:
    build: ./face-bokeh
    ports:
      - "8001:8000"
    environment:
      - TRITON_URL=triton:8000
    depends_on:
      - triton

  emotion:
    build: ./face-emotion
    ports:
      - "8002:8000"
    environment:
      - TRITON_URL=triton:8000
    depends_on:
      - triton
    
  main:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVICE_BOKE=http://boke:8000
      - SERVICE_EMOTION=http://emotion:8000
    depends_on:
      - emotion
      - boke
    
    


