version: "3"

services:
  triton:
    image: "nvcr.io/nvidia/tritonserver:22.06-py3"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: ["tritonserver","--model-repository=${S3_BUCKET_NAME}"]
    


